---
- name: Configure ci-master
  hosts: ci-master
  become: yes

  tasks:

    - name: Install Java
      apt:
        name: openjdk-21-jre
        state: present
        update_cache: yes

    - name: Install Jenkins dependencies
      apt:
        name:
          - fontconfig
          - wget
        state: present

    - name: Add Jenkins repository key
      shell: |
        mkdir -p /etc/apt/keyrings
        wget -O /etc/apt/keyrings/jenkins-keyring.asc \
        https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Verify Jenkins
      command: systemctl is-active jenkins
      register: jenkins_status

    - name: Show Jenkins status
      debug:
        msg: "Jenkins status: {{ jenkins_status.stdout }}"


- name: Configure ci-agent
  hosts: ci-agent
  become: yes

  tasks:

    - name: Install Java
      apt:
        name: openjdk-21-jre
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Verify Docker
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        msg: "{{ docker_version.stdout }}"
